# Generated by Django 5.2.8 on 2025-11-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='facrory_year',
            new_name='factory_year',
        ),
    ]
