# Generated by Django 5.2.8 on 2025-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory_alter_car_brand_alter_car_factory_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
